### ISSUE TITLE
[Feat] Add a sign-in and login with other accounts options

### ISSUE THREAD

**Issue by sania-2912** [mdazfar2/Ezyshop#1003]
### Description

add a sign-in and login with other accounts such as google, facebook and instagram options to make it easier for customers as well as sellers

### Screenshots

![Screenshot 2024-10-27 184721](https://github.com/user-attachments/assets/019bc1c6-996e-477f-8dde-d27c3bf18fc0)
![Screenshot 2024-10-27 184709](https://github.com/user-attachments/assets/2e6a8c1d-6f43-4be8-9948-6d7a5800fc27)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @sania-2912, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.
