### ISSUE TITLE
[Feat]Implement Chatbot Feature

### ISSUE THREAD

**Issue by Ankul8471** [mdazfar2/Ezyshop#1020]
### Description

Description: Implement a chatbot feature that assists users by generating relevant titles and descriptions for their content. This feature will improve user experience by helping users create optimized and engaging text based on their input.

Proposed Solution:

User Prompting: The chatbot should ask users key questions about their content, purpose, and audience.
Natural Language Processing (NLP): Use NLP to process responses and generate suitable titles and descriptions.
Customizable Output: Allow users to tweak the generated output to meet their specific needs.
Benefits:

Provides users with quick, optimized title and description suggestions.
Improves engagement by generating descriptive, engaging, and SEO-friendly text.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Ankul8471, ChatBOT is a very good feature, but I don’t think it is needed on our website right now. Once the website is fully functional and in working condition, I will let you know. Currently, we are working on the payment gateway, so I will inform you if there is a need in the future. Please raise any other issue, which I am happy to assign to you, but make sure the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_

**Comment by Ankul8471** [comment]
Ok I understand it but you assign me then it will help me a lot leaderboard and gssoc and also assigned some in future then why not now

**Comment by mdazfar2** [comment]
@Ankul8471, don't worry. We retrieved your issues from the closed section and will add you there if a chatbot is needed.

Ankul, tell me one thing. In a previous issue, I reopened the issue for multilingual language support and assigned it to you, asking you to star our repository, which you acknowledged. However, I still noticed that you haven't starred it. Is this the right way to contribute to open source?

- I also assume you haven't read our contributing guidelines. Please don't do that.

**Comment by Ankul8471** [comment]
Ok I will do this
