### ISSUE TITLE
[Feat] add custom cursor

### ISSUE THREAD

**Issue by amanver45** [mdazfar2/Ezyshop#1022]
### Description

custom cursor for website

### Screenshots

sometthing ike this
https://github.com/user-attachments/assets/05da1b5c-f417-4307-9cb0-4e6fdfb48471

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by amanver45** [comment]
@mdazfar2 .....

**Comment by mdazfar2** [comment]
Hey @amanver45, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly.


- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


***Thank you!***

**Comment by amanver45** [comment]
@mdazfar2 can i integrate chatbot its simply placed in right corner of website without changig alignment of website  it helpusers

**Comment by mdazfar2** [comment]
@amanver45 It was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.


- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


***Thank you!***

**Comment by amanver45** [comment]
@mdazfar2  I see that issue but it's more than one week and no respone on issue may be he is not working on issue that's why I am asking

**Comment by mdazfar2** [comment]
@amanver45, mention me on the issue that has been open for over 4 days with no response, and I will assign it.
