### ISSUE TITLE
Chat Bot Integration 

### ISSUE THREAD

**Issue by Molza01** [mdazfar2/Ezyshop#1035]
### Description

There should be a ChatBot integration in the website which will enhance the user surfing experience and also resolve all the doubts of the user regarding the content.

### Screenshots

\![Screenshot 2024-10-30 014323](https://github.com/user-attachments/assets/93a123e4-901c-40ac-934b-0340b46081d6)

So please assign me this issue under
Name : Sandesh Shinde
Label : gssoc

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Molza01, ChatBOT is a very good feature, but I don’t think it is needed on our website right now. Once the website is fully functional and in working condition, I will let you know. Currently, we are working on the payment gateway, so I will inform you if there is a need in the future. Please raise any other issue, which I am happy to assign to you, but make sure the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_

**Comment by Molza01** [comment]
@mdazfar2 ok then, let me know in future if it's needed.
Thank you for your response.

**Comment by mdazfar2** [comment]
> @mdazfar2 ok then, let me know in future if it's needed.
> Thank you for your response.




Sure.
