### ISSUE TITLE
Add hover effect to navbar

### ISSUE THREAD

**Issue by vidhyadhari-11** [mdazfar2/Ezyshop#1063]
i want to add the hover effect when we place our cursor on the navbar we can see line appearing and then disappear when cursor is removed 

![WhatsApp Image 2024-11-04 at 21 07 57](https://github.com/user-attachments/assets/90d43649-3cf6-403c-96b0-5623bb7378fe)

**Comment by mdazfar2** [comment]
Hey @vidhyadhari-11, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. **Thank you!**
