### ISSUE TITLE
[Feat] Implement Newsletter Functionality

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#1069]
### Description

# Issue Description: Implement Newsletter Functionality

## Overview

We need to implement a newsletter subscription functionality on our platform, Ezyshop. This feature will allow users to enter their name and email to subscribe to our newsletter. Upon successful subscription, users will receive a confirmation email.

## Requirements

1. **Subscription Form**:
   - Create a form where users can enter their name and email address.
   - Include a "Subscribe" button to submit the form.

2. **Email Confirmation**:
   - Upon subscription, users should receive a confirmation email from Ezyshop.
   - Use a third-party email service (e.g., SendGrid, Mailgun) for sending emails.

3. **Database Storage**:
   - Store user details (name and email) in our MongoDB database to track subscriptions.
   - Ensure that the database schema is updated accordingly to handle subscriptions.

4. **Duplicate Subscription Handling**:
   - If a user tries to subscribe again using an already registered email, a popup message should appear stating: "Already subscribed to our newsletter."
   - Ensure that the frontend and backend properly handle this scenario to prevent duplicate entries in the database.

## Additional Notes

- Please provide guidance on the best practices for implementing email confirmation and subscription tracking.
- Ensure that the code is well-documented and follows our coding standards.

## Acceptance Criteria

- A functional subscription form that captures user input.
- Confirmation emails are sent successfully upon subscription.
- User details are stored in MongoDB without duplicates.
- The user receives a friendly error message when trying to subscribe with an existing email.

---

Let me know if you can implement this functionality and if you need any additional information or resources to get started.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays You are assigned.

Try to implement the newsletter functionality, so that when a user enters their name and email and clicks the `subscribe` button, they receive an email from Ezyshop, Additionally, can the user details be stored in my MongoDB database to track subscriptions, If a user tries to subscribe again with an already registered email, a popup should appear saying, `Already subscribed to our newsletter`. Let me know if you can implement this.

<br/>


**Checkout the below demo video for better understand** 👇


<br>

https://github.com/user-attachments/assets/a7833364-4b0d-4821-85e4-dd20ac3df8b6

**Comment by ShivanshPlays** [comment]
okay understood
