### ISSUE TITLE
[Feat] Add 

### ISSUE THREAD

**Issue by Richajaishwal0** [mdazfar2/Ezyshop#1090]
### Description

I have Considered alternatives that includes Single Sign-On with Microsoft/LinkedIn, Two-Factor Authentication, Magic Link email login.

### Screenshots

![image](https://github.com/user-attachments/assets/ca44165f-dd54-4842-a7ff-f9cfe298cbee)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Richajaishwal0, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.
