### ISSUE TITLE
Change the Twitter icon to X icon

### ISSUE THREAD

**Issue by Bhanuprakash842** [mdazfar2/Ezyshop#158]
### Description

I want to change the Twitter icon to the X icon.I would be grateful if you assign me this issue under gssoc-ext,hacktoberfest-accepted.my GitHub username is @Bhanuprakash842

### Screenshots

![IMG_20241004_214019](https://github.com/user-attachments/assets/e71da310-a7ea-4ee4-92ae-05ac1b13773c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Bhanuprakash842 you are assigned.

Do one thing: instead of the Twitter icon, add the `GitHub` icon and insert the Ezyshop GitHub repo link. In the `LinkedIn` icon, insert the LinkedIn link found in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md), and instead of Facebook, add the Discord icon and include the Discord invite link, which is also available in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md).
