### ISSUE TITLE
[BUG] Footer social links are not working

### ISSUE THREAD

**Issue by 9AB5** [mdazfar2/Ezyshop#208]
### Description

Description:

The Social Links in the Footer of the Site is not redirecting to anything.

### Screenshots

[
![Screenshot 2024-10-05 235439](https://github.com/user-attachments/assets/61aca19e-a01a-44ad-becd-49be70b49c9c)
](url)

### Any additional information?

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by 9AB5** [comment]
@mdazfar2 kindly assign me this issue,also can i get the social media links to update the footer with it?

**Comment by ChauhanAyush04** [comment]
@mdazfar2  plz assign me this

**Comment by mdazfar2** [comment]
@9AB5 do one thing: instead of the Twitter icon, add the GitHub icon and insert the Ezyshop GitHub repo link. In the LinkedIn icon, insert the LinkedIn link found in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md), and instead of Facebook, add the Discord icon and include the Discord invite link, which is also available in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md).
