### ISSUE TITLE
[Feat] Creating a db modal for user to register

### ISSUE THREAD

**Issue by ayush-848** [mdazfar2/Ezyshop#342]
### Description

To keep the user in mongo db instaed of local storage

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ayush-848** [comment]
@mdazfar2 please assign this issue to me

**Comment by Kavita1928** [comment]
@ayush-848 assigned

**Comment by Siddhi-sahu** [comment]
are you done @ayush-848 or i would like to work on it

**Comment by ayush-848** [comment]
> are you done @ayush-848 or i would like to work on it

@Siddhi-sahu I am getting some problems while cloning it. So ya you can do it

**Comment by Siddhi-sahu** [comment]
okay so how do i take this issue up so that i get the points @mdazfar2 @ayush-848

**Comment by ayush-848** [comment]
> okay so how do i take this issue up so that i get the points @mdazfar2 @ayush-848

Before that please check that you can successfully clone it

**Comment by ayush-848** [comment]
@Kavita1928 should i give firebase based login coz this app is frontend based only so usermodal is not required

**Comment by mdazfar2** [comment]
Hey @ayush-848, I really appreciate your enthusiasm with authentication, but we have removed the authentication feature and will only add mobile number OTP, name, email, etc., because adding authentication is not ideal for an E-commerce website. Hope you understand. Please search for any other issue, which I'm happy to assign to you.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
