### ISSUE TITLE
[Feat]Adding Login or sign up via Google functionality

### ISSUE THREAD

**Issue by Ankitha2130** [mdazfar2/Ezyshop#396]
### Description

I will work this issue of adding login via google functionality.
Please assign this issue to me under gssoc-ext, hacktoberfest, and a suitable level label.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@Ankitha2130 assigned ,Now you can work on this

**Comment by Kavita1928** [comment]
@Ankitha2130  any update ?

**Comment by Ankitha2130** [comment]
ya almost done by today afternoon i will make the pull request

**Comment by Ankitha2130** [comment]
Can you please share your mail id so that i can connect it with your mail id.

**Comment by mdazfar2** [comment]
Hey @Ankitha2130, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our Discord for the latest website announcements and features.

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
