### ISSUE TITLE
[Feat]Add more details in online shopping description

### ISSUE THREAD

**Issue by mansi066** [mdazfar2/Ezyshop#400]
### Description

I want to add in the description like
MATERIAL
FIT
DESIGN 
COLORS
CARE INSTRUCTIONS
OCASSION

**ADVANTAGES OF ADDING DESCRIPTION**
**Enhanced User Experience:** Clear, detailed information helps customers make informed decisions quickly.

**Increased Trust:** Transparency about materials, fit, and care instructions builds customer trust and confidence in the product.

**Higher Conversion Rates:** Comprehensive details can persuade potential buyers, reducing hesitation and increasing purchase likelihood.

**Reduced Returns:** Accurate descriptions ensure customers know what to expect, decreasing the chances of dissatisfaction and returns.

### Screenshots

[
![Screenshot 2024-10-10 135843](https://github.com/user-attachments/assets/bc826a23-d692-4ee3-a5d0-73263ebcf4c1)
](url)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mansi066** [comment]
@mdazfar2 Please assign me I want to work on this issue.

**Comment by mansi066** [comment]
![Screenshot 2024-10-11 135545](https://github.com/user-attachments/assets/4c3d7803-fc1b-4527-8aac-efd3a1b74c46)
![Screenshot 2024-10-11 135533](https://github.com/user-attachments/assets/754b5417-7aa8-4c60-a0ed-eb481bf591b7)

Check the screenshot .Let me know koi aur change Chhaiya toh.

**Comment by mansi066** [comment]
![Screenshot 2024-10-11 135909](https://github.com/user-attachments/assets/1bc0320f-aee4-4e99-beed-66cd6606777e)
This wil open after clicking on the image.

**Comment by mansi066** [comment]
Please add the level.

**Comment by mdazfar2** [comment]
Hey @mansi066, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our Discord for the latest website announcements and features.

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
