### ISSUE TITLE
[Feat]Add Login and Signup Page UI to Enhance User Authentication Flow

### ISSUE THREAD

**Issue by Blessy-B-Sherin** [mdazfar2/Ezyshop#43]
### Description

Currently, EzyShop lacks a login and signup page, which are essential for securing user accounts and providing a personalized shopping experience. I propose designing and implementing a user-friendly **Login** and **Signup** page for the platform. These pages will be styled in accordance with the app's existing design language and include form validation for better user experience.

**Proposed Features:**
1. **Login Page:**
   - Fields for email/username and password.
   - A "Forgot Password" link for users who need to reset their credentials.
   - "Remember Me" checkbox for convenience.
   - A button to navigate to the signup page if the user doesn't have an account.

2. **Signup Page:**
   - Fields for user details such as name, email, phone number, and password.
   - Basic form validation to ensure proper inputs (e.g., email format, password strength).
   - Option for users to agree to the terms and conditions.
   - A button to navigate to the login page if the user already has an account.

I can handle the **frontend part**, including HTML, CSS, and JavaScript for form validation and UI enhancements. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Blessy-B-Sherin, that's great! We need it, but please wait a while. We will notify you to work on this issue. Actually, someone else is working on that page, so I would ask you to wait for a while; otherwise, a conflict may occur. Hope you understand.

- Don't forget to join our official [Discord server](https://discord.gg/SEzpxqQG).
- And also follow us on [Linkedin](https://linkedin.com/company/Ezyshopz/)
- And please ⭐ our repo
