### ISSUE TITLE
Make the newsletter section more interactive

### ISSUE THREAD

**Issue by ThunderShadows** [mdazfar2/Ezyshop#450]
The newsletter section is dull and has less responsive styling in it.

@mdazfar2 

I shall make the newsletter section more interactive and responsive for users while filling the form. Including CSS styling and animations to buttons.

**Comment by Kavita1928** [comment]
@ThunderShadows provide a screenshot after the modification you want 
and first make sure to star our Repo[https://github.com/mdazfar2/Ezyshop]

**Comment by ThunderShadows** [comment]
![image](https://github.com/user-attachments/assets/e99b5c5c-16f1-421e-83fe-bd493543e86e)

Something similar to this

**Comment by Kavita1928** [comment]
@ThunderShadows  Okk ,go for it

**Comment by mdazfar2** [comment]
Hey @ThunderShadows, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.

**Comment by ThunderShadows** [comment]
> Hey @ThunderShadows, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.
> 
> * And also please give Star us ⭐
> * Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.

Thank you for your time Sir. I appreciate it.
