### ISSUE TITLE
[Feat]: Add Multilingual Support

### ISSUE THREAD

**Issue by PavanTeja2005** [mdazfar2/Ezyshop#457]
### Description

I will add multilingual support to the website so that all pages' content can be translated to different selected language in according to the language selected by the user.

Benefits
- Improved User Experience: Users can navigate in their preferred language.
- Scalability: Easily add new languages in the future.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by PavanTeja2005** [comment]
Please add a label as we were asked to make sure to have labels

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by PavanTeja2005** [comment]
Heyy @SaanyaGarg5 I have already raised a PR

**Comment by mdazfar2** [comment]
Hey @rajdeepchakraborty-rc, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 Firstly, I'm sorry to hear about your health issues, and I hope you recover quickly. Additionally, I haven't opened this PR yet. Could you please clarify why you mentioned me?
