### ISSUE TITLE
[Feat] Feature Request: Add User Authentication with JWTs

### ISSUE THREAD

**Issue by Siddhi-sahu** [mdazfar2/Ezyshop#458]
### Description

Hello, I’d like to propose adding user authentication using JSON Web Tokens (JWTs) to the project. Currently, there is no user authentication system in place, and implementing JWT-based authentication would significantly enhance security and allow for personalized user experiences on the platform.

Technical Considerations:

Backend API: JWTs require a backend server (such as Node.js) for token generation and verification.
Token Validation: The frontend can send the token in the authorization header with each request to ensure the user is authenticated.
Since this would involve transitioning the project to Node.js and adding user validation, I kindly request you consider assigning this issue a level3 label for its complexity and scope. 😊

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Siddhi-sahu** [comment]
@thakuratul2 @Kavita1928 kindly assign me this

**Comment by mdazfar2** [comment]
Hey @Siddhi-sahu, I really appreciate your enthusiasm with authentication, but we have removed the authentication feature and will only add mobile number OTP, name, email, etc., because adding authentication is not ideal for an E-commerce website. Hope you understand. Please search for any other issue, which I'm happy to assign to you.



- Actually we're getting very close to 100 stars!  Would you mind giving our [repository](https://github.com/mdazfar2/ezyshop/) a star?  ⭐
