### ISSUE TITLE
[Feat] Adding Toast rather than simple alerts

### ISSUE THREAD

**Issue by Sourabh782** [mdazfar2/Ezyshop#549]
### Description

Currently for telling success and displaying message dureing signup and login we are seeing alerts which stops execution, instead i wanted to implement toast functionality for displaying messages

### Screenshots

![image](https://github.com/user-attachments/assets/4143783b-f098-4ab0-81e6-732e6246d59d)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by spc-28** [comment]
please assign this issue to me

**Comment by mdazfar2** [comment]
Hey @Sourabh782, can you please share a demo video of the type of alert you want to contribute?

- Star our repository ⭐

**Comment by Sourabh782** [comment]
@mdazfar2 can I share ss?

**Comment by mdazfar2** [comment]
Sure @Sourabh782

**Comment by Sourabh782** [comment]
> Sure @Sourabh782

![image](https://github.com/user-attachments/assets/d7ae9c2e-9ff9-4928-b315-2aace48cf951)

like this, its currently toastify-js

**Comment by Sourabh782** [comment]
And also, like you guys are changing project to next, may i know how can i contribute if i wanted to help?

**Comment by mdazfar2** [comment]
Hey @Sourabh782, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
