### ISSUE TITLE
[Feat] implementing Login and signup functionality in Next.js

### ISSUE THREAD

**Issue by Sourabh782** [mdazfar2/Ezyshop#551]
### Description

hii @mdazfar2,  i saw you guys are implementing this app in next js, i have good knowledge of implementing backend routes in next js with practical experience in contributing in 3 projects in gssoc extd, i think i can help implementing the functionality

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Sourabh782, I really appreciate your enthusiasm with login/signup, but we have removed the authentication feature and will only add mobile number OTP, name, email, etc., because adding authentication is not ideal for an E-commerce website. Hope you understand. Please search for any other issue, which I'm happy to assign to you.


- Sourabh, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐
