### ISSUE TITLE
Our Facilities section header is not centre aligned

### ISSUE THREAD

**Issue by sneha056** [mdazfar2/Ezyshop#562]
### Description

Hey @mdazfar2 please assign me this task( #562)
As every section heading is centre aligned but in home page facilities section header is not centre aligned which makes pin out of whole website.

### Screenshots

![Screenshot 2024-10-13 181505](https://github.com/user-attachments/assets/ad0343c2-6679-4dd9-83ce-05649d0371ce)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @sneha056, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
