### ISSUE TITLE
[BUG] Start shopping button is not working in the home page

### ISSUE THREAD

**Issue by poojitha-ch** [mdazfar2/Ezyshop#567]
### Description

when clicking on start shopping it is not directing me anywhere.

### Any additional information?

Could you please assign me this issue.
I would like to work on it @mdazfar2 , @Kavita1928 , @thakuratul2.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by tobiasrahul** [comment]
Can You Please assign me this issue to work upon. I have great experience in frontend developmenet and worked as an intern in Metacrafters.

**Comment by Kavita1928** [comment]
@poojitha-ch Where you will be pointing it ?please make sure to explain the issue properly  and star our [Repo](https://github.com/mdazfar2/Ezyshop).

**Comment by poojitha-ch** [comment]
> @poojitha-ch Where you will be pointing it ?please make sure to explain the issue properly and star our [Repo](https://github.com/mdazfar2/Ezyshop).

![image](https://github.com/user-attachments/assets/4befcf1a-9eb3-46cd-bbb4-488b1983db63)
I think pointing it here would be a better option so that they can explore items more  easily rather than not directing it to anywhere.
Yes, I have starred the repository.

**Comment by mdazfar2** [comment]
Hey @poojitha-ch, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
