### ISSUE TITLE
[Feat] Add Exclusive Discounts & Offers page/pop-up

### ISSUE THREAD

**Issue by Anwishta** [mdazfar2/Ezyshop#570]
### Description

I propose adding an Exclusive Discounts & Offers page or pop-up to showcase special promotions, discounts, and limited-time offers available to users. This feature aims to increase user engagement, drive sales, and reward loyal customers with exclusive deals. The page or pop-up will be easily accessible and customizable, ensuring that users are informed about ongoing promotions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Anwishta, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
