### ISSUE TITLE
[Feat] Add Icons to Navigation Menu for Improved User Experience

### ISSUE THREAD

**Issue by Sanikaaher-19** [mdazfar2/Ezyshop#572]
### Description

Adding icons next to each navigation item will make the menu visually attractive, breaking the monotony of text-only navigation.
Icons can convey meaning quickly, allowing users to identify sections of the website at a glance.

Icons can enhance the intuitive nature of the navigation menu. Users often associate certain icons with specific actions or pages (e.g., a house icon for Home, an envelope for Contact Us).
This improvement can lead to faster navigation, as users can easily find what they are looking for without reading through text.

### Screenshots

![shopwebsite contentnav icon](https://github.com/user-attachments/assets/351f4313-2c73-4872-b9d3-a154d473d5c5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Sanikaaher-19** [comment]
@mdazfar2
Please Review - Add Icons to Navigation Menu for Improved User Experience

**Comment by Kavita1928** [comment]
@Sanikaaher-19 I don't think icons will suit for all navbar commands but once provide a screenshot of it after making changing in website

**Comment by Sanikaaher-19** [comment]
sure!

**Comment by mdazfar2** [comment]
Hey @Sanikaaher-19, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
