### ISSUE TITLE
Latest Article link on homepage not working

### ISSUE THREAD

**Issue by 9AB5** [mdazfar2/Ezyshop#578]
### Description

Description:
The links having name "Read More" from the section of "Latest Articles From Blog" on Home page of website are not working.
They are simply redirecting to top of home page.

### Screenshots

Scrrenshot:
![Screenshot 2024-10-13 230141](https://github.com/user-attachments/assets/9f1e8ca8-0078-4caf-8ba0-54c6259b0d95)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @9AB5, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
