### ISSUE TITLE
[Feat] Add Animation Effect to the Card Section

### ISSUE THREAD

**Issue by 13Sharad** [mdazfar2/Ezyshop#586]
### Description

🔴 Tech stack:

CSS
JavaScript (optional for advanced animations)
🔴 Objective:

Enhance the user experience on the EzyShopz website by adding smooth animation effects to the product cards. This will make the site more interactive and visually appealing, encouraging user engagement.

🔴 Summary:
The card section on the website currently displays products statically. By adding animations such as hover effects, fade-in, or zoom, the cards will become more dynamic. When a user hovers over a card, it could enlarge slightly, display additional product information, or show subtle transitions that improve overall interaction and aesthetics.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by rohitmore07** [comment]
Hey @mdazfar2 I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by mdazfar2** [comment]
Hey @rohitmore07 @13Sharad , sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
