### ISSUE TITLE
[Feat]  Add FAQ (Frequently Asked Questions) Section to the Website

### ISSUE THREAD

**Issue by 13Sharad** [mdazfar2/Ezyshop#587]
### Description

🔴 Tech stack:

HTML
CSS
JavaScript (optional for collapsible or interactive FAQ)

🔴 Objective:

Provide users with a dedicated section to address common queries and provide detailed answers, improving user experience by offering quick access to essential information.

🔴 Summary:

The FAQ section will help visitors quickly find answers to common questions regarding EzyShopz services, shipping policies, product details, returns, and more. By organizing the most frequently asked questions in an easily navigable format, users can save time and reduce the need to contact support. Optionally, adding collapsible questions with JavaScript will create a clean, user-friendly layout that doesn’t overwhelm the page.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Kavita1928** [comment]
@13Sharad  asssigned and make sure to star our [Repo](https://github.com/mdazfar2/Ezyshop).

**Comment by 13Sharad** [comment]
@Kavita1928 Please added the Level.

**Comment by Subham1** [comment]
@Kavita1928 could you pls assign me this work

**Comment by 13Sharad** [comment]
@Kavita1928 please merged this pull request

**Comment by mdazfar2** [comment]
Hey @Subham1 @13Sharad , sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
