### ISSUE TITLE
[Feat]Add Pre-loader

### ISSUE THREAD

**Issue by soumyajit254** [mdazfar2/Ezyshop#595]
### Description

Add pre-loader

### Screenshots

![Screenshot 2024-10-14 094017](https://github.com/user-attachments/assets/7568e0f5-57a8-419f-9ce1-48a6dd2073ec)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by soumyajit254** [comment]
Please assign this project. I can add pre-loader.

**Comment by Kavita1928** [comment]
@soumyajit254 assigned

**Comment by Peart-Guy** [comment]
@Kavita1928 
I can work on this issue. 
I am providing a basic sample . The final product may vary depending on your specific needs and preferences.

https://github.com/user-attachments/assets/29d357a2-9c82-4a76-a84b-cbc483d4cde6

**Comment by mdazfar2** [comment]
Hey @soumyajit254, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
