### ISSUE TITLE
[Feat]:Adding AOS,js scrolling animation to the website 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [mdazfar2/Ezyshop#627]
### Description

Adding AOS,js scrolling animation to the website 

### Screenshots

![image](https://github.com/user-attachments/assets/9a196a1d-44d9-4194-ae47-5fd9391bde02)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal share demo screen record of your changes

**Comment by gnjayasekara** [comment]
I would like to work on this feature. Could you assign this to me.

**Comment by mdazfar2** [comment]
Sorry @gnjayasekara, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. ***Thank you!***
