### ISSUE TITLE
[BUG] navbar bug

### ISSUE THREAD

**Issue by Prudhvi-232** [mdazfar2/Ezyshop#631]
### Description

if we see navbar in home page it doesn't contain shops column in the navbar and in shops page the pages column is missing

### Screenshots

Uploading Recording 2024-10-14 230252.mp4…

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Prudhvi-232, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
