### ISSUE TITLE
[Feat]: Display user Avatar

### ISSUE THREAD

**Issue by haseebzaki-07** [mdazfar2/Ezyshop#635]
### Description

After the user signs up successfully he/she should see their Avatars with the first name of the letter instead of the Login/Signup button. This makes the experience of the user more personalized rather making confusions whether the user is signed in or not.

### Screenshots

![Screenshot 2024-10-15 000329](https://github.com/user-attachments/assets/01c460be-6805-4fe0-bfda-c5339262c67e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @harith-hacky03, one issue can be assigned to only one person at a time. Please don't be discouraged; you can raise a new one that is really needed for our website, where I'm happy to assign you.


- Actually, I need to reach a total of 128 stars to get the Starstruck x2 badge achievement on my GitHub. Can you please help by Star our [repository](https://github.com/mdazfar2/ezyshop/)? ⭐

**Comment by mdazfar2** [comment]
Sorry @haseebzaki-07 Actually I send this message to another one.

Actually this is already done on our website. The username will be shown after successfully logging in or creating your account. That's why I closed this issue. Please raise another issue, which I'm happy to assign to you.

- please don't discourage bro.

- Please don't forget to give our [repository](https://github.com/mdazfar2/ezyshop) a star and let me know once you've done it.

**Comment by haseebzaki-07** [comment]
@mdazfar2 No worries bro, I raised this issue because I saw after successful login the avatar is not rendered, because of which I raised the issue. So yes there is still a bug. Do you suggest me to raise another issue addressing this.
I have starred the repo.
