### ISSUE TITLE
The font color could be changed in the footer section

### ISSUE THREAD

**Issue by iamasraful** [mdazfar2/Ezyshop#644]
### Description

I saw the font color in the footer section, that is ruining the User Experience. It could be changed.

### Screenshots

![image](https://github.com/user-attachments/assets/253c5676-0b9d-43ff-9ec8-d0e6883a2bfa)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @username, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
