### ISSUE TITLE
[BUG]-Misalignment and Duplicate Content on the Contact Us Page

### ISSUE THREAD

**Issue by MadhavDhatrak** [mdazfar2/Ezyshop#647]
### Description

**The "Contact Us" page has multiple issues that need to be addressed:**

-1.Misalignment of the Inputs: The input fields on the page are not properly aligned, causing the layout to appear unstructured.
-2.Duplicate Content: There is duplicate content in both the header and footer, which affects the user experience and needs to be removed or adjusted.

### Screenshots

![Screenshot (466)](https://github.com/user-attachments/assets/88fedf52-75b8-47e8-95b8-bea932f41699)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by MadhavDhatrak** [comment]
@Kavita1928 @mdazfar2 Assign this issue to me under Hacktoberfest and GSSoC-Ext."

**Comment by mdazfar2** [comment]
Hey @MadhavDhatrak, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
