### ISSUE TITLE
[Feat]Add Contributors Section on the About Us Page

### ISSUE THREAD

**Issue by GAURAV8520** [mdazfar2/Ezyshop#653]
### Description:
We are introducing a new feature on the "About Us" page to display details of all project contributors. This section will showcase the following information for each contributor:

- **Name**
- **Profile Image (from GitHub)**
- **GitHub Profile Link**

### Feature Details:
- **Section Title:** Contributors
- **Information Displayed:**
  - Contributor's Name
  - Profile Image (from GitHub)
  - GitHub Profile Link
- **API Integration:**
  - Fetch contributors' data from the GitHub repository's contributor list using the GitHub API (or manually, if needed).
- **Design:**
  - The layout should be consistent with the overall design of the "About Us" page.
  - Make it responsive for both desktop and mobile views.
- **Optional Enhancement:**
  - Automatically update the list when new contributors are added to the repository.

### Tasks:
1. Fetch contributors' data from the GitHub API or create a JSON file with contributors' names, image URLs, and GitHub links.
2. Design and develop a new section on the "About Us" page to display the contributors.
3. Ensure the design is responsive across all devices.
4. Test the new section for any bugs or issues.

### Additional Context:
This feature will help acknowledge the work of all contributors and encourage further open-source collaboration on this project.

### Example:

![Screenshot 2024-10-15 141810](https://github.com/user-attachments/assets/ff1bcca0-bda8-41cf-b317-ea46920c5121)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @GAURAV8520, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
