### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by rutikakengal** [mdazfar2/Ezyshop#654]
This chatbot gives answers to every question and give fast response to users , Assign me I like to work on it @mdazafar2

**Comment by mdazfar2** [comment]
Hey @rutikakengal, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
