### ISSUE TITLE
Footer part is not visible  clear

### ISSUE THREAD

**Issue by shrutilad20** [mdazfar2/Ezyshop#660]
![image](https://github.com/user-attachments/assets/23929ce0-5860-4b2c-b69f-222f18d10e5e)

footer part isn't clear because the font color is not visible

**Comment by mdazfar2** [comment]
Hey @shrutilad20 @hrpofficial736 , sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
