### ISSUE TITLE
[Feat] adding multi language support system

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [mdazfar2/Ezyshop#695]
### Description

I want to add multi language support system to the website which can help us understand in their native language.
@mdazfar2 can you assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by T-Rahul-prabhu-38** [comment]
@mdazfar2 can i work on this.

**Comment by mdazfar2** [comment]
Hey @T-Rahul-prabhu-38, as you previously raised the issue and I closed it, I mentioned that our website only supports India, so I don't think this feature will be needed.

The website requires multilingual support for global usage, where it's understood that everyone knows English, with just minor adjustments.

If we need this feature in the future, we will definitely let you know.

Please don't be discouraged. I need to close your issue. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and truly needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_
