### ISSUE TITLE
[Feat] Improving the home page UI completely

### ISSUE THREAD

**Issue by J-B-Mugundh** [mdazfar2/Ezyshop#768]
### Description

Currently, I could feel the webpage as very static and feels a bit engaging and attractive. I want to enhance the syling and the feel of the complete site to a next level. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by J-B-Mugundh** [comment]
@mdazfar2 Please assign me this issue.. based on my work satisfaction, you can change the level.

**Comment by J-B-Mugundh** [comment]
@mdazfar2 May I please know why it's closed? I'm adding a feature which is not present + I've searched that this issue isn't there. Atleast, you could add the reason for closing this issue.

**Comment by mdazfar2** [comment]
Hey @J-B-Mugundh, sorry for the late reply. I’ve been a little busy due to my health condition. We have converted the entire code to Next.js and Tailwind CSS for better backend integration. You raised a good issue, but it was based on the old HTML and CSS version. We’ve moved everything to Next.js and Tailwind CSS. Please look into that, and don’t forget to join our [Discord Server](https://discord.gg/Rg8T5gtE)for the latest website announcements and features.

- And also please give Star us ⭐

- Please don't be discouraged. I will close the issue for now, but you can raise a new one that is truly needed for our website. Thank you.
