### ISSUE TITLE
[Feat] Add a Translation Tool (all language) ⭐

### ISSUE THREAD

**Issue by Subhajit-2023-44** [mdazfar2/Ezyshop#825]
### Description

I want to add a Translation Tool(all language) properly.

@mdazfar2  PA please assign me this task.

![Screenshot 2024-10-20 211104](https://github.com/user-attachments/assets/3cc8f1f0-1abb-45d4-8a33-def818ffcbcd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @rajdeepchakraborty-rc The website requires multilingual support for global usage, where it's understood that everyone knows English, with just minor adjustments.

If we need this feature in the future, we will definitely let you know.

Please don't be discouraged. I need to close your issue. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and truly needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_

**Comment by rajdeepchakraborty-rc** [comment]
@mdazfar2 I have not opened this PR. Could you please take a moment to check the contributors who have opened the issue and mention them in your reply? Thank you! Hppe you have a wonderful day ahead 😄

**Comment by mdazfar2** [comment]
Sorry @rajdeepchakraborty-rc

**Comment by rajdeepchakraborty-rc** [comment]
> Sorry @rajdeepchakraborty-rc

@mdazfar2 You don't have to be sorry, it's ok. I realize it’s more challenging for all of you to manage everything and review the PRs. Please make sure to take care of your health, and I hope you feel better soon.
