### ISSUE TITLE
Implement Log-In via Google, GitHub, Facebook, and LinkedIn

### ISSUE THREAD

**Issue by sriharsha0x1** [mdazfar2/Ezyshop#849]
### Description

Currently, the website does not offer social media login options such as Google, GitHub, Facebook, or LinkedIn. Implementing these sign-in methods will improve user convenience by allowing quick and secure authentication through widely-used platforms, reducing the need to create and manage separate accounts.

Could you please assign me this? @mda

### Screenshots

![image](https://github.com/user-attachments/assets/955f7068-124f-4a52-b561-5f2d0225fb1e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @sriharsha0x1, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.
