### ISSUE TITLE
[Feat] Integrate Google Sign-In with NextAuth

### ISSUE THREAD

**Issue by ShobhitPatra** [mdazfar2/Ezyshop#866]
### Description

Currently, the project supports user registration and sign-in through credentials-based authentication using NextAuth. To enhance the user experience and provide more sign-in options,want to integrate Google Sign-in using NextAuth's built-in Google provider. This will allow users to authenticate via their Google accounts seamlessly.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ShobhitPatra, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.
