### ISSUE TITLE
[Feat] Dockerize The App

### ISSUE THREAD

**Issue by ShobhitPatra** [mdazfar2/Ezyshop#868]
### Description

To simplify deployment and ensure consistency across environments, the application needs to be containerized using Docker. This setup will enable smooth transitions between development and production environments, providing scalability and better resource management.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @ShobhitPatra, issue acknowledged! Please provide a Dockerfile that allows me to successfully create an image and run a fully functional container.

**Comment by A7Lavinraj** [comment]
I want to work on it

**Comment by mdazfar2** [comment]
Sorry @A7Lavinraj, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. ***Thank you!***

**Comment by mdazfar2** [comment]
No @ShobhitPatra It is useful

**Comment by ShobhitPatra** [comment]
@mdazfar2 what should I do, comment out those lines just for now and build the project or write the Docker file just for development.?
