### ISSUE TITLE
[Feat]: Add a Cursor Tail Effector 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [mdazfar2/Ezyshop#897]
### Description

Implement a Cursor Tail Effector that creates a visual tail effect following the mouse cursor. This feature should enhance user interaction by providing a dynamic visual element that responds to cursor movement.

Requirements:

- The tail should consist of a customizable number of segments.
- Tail segments should smoothly follow the cursor with a slight delay.
- Provide options for customization (color, length, and segment count).

PA @mdazfar2, please assign me this issue.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @AnushkaChouhan25, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. **Thank you!**
