### ISSUE TITLE
[Feat] Implementing Logic for "download invoice" for PDF Generation

### ISSUE THREAD

**Issue by ParasY1724** [mdazfar2/Ezyshop#908]
### Description

**Description:**
PDF Generation For Invoice  Fore Orders by using pdf-lib module .This invoice will contain watermark of shop logo.
I have work on similar feature before.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ParasY1724 That's amazing, but can you please tell me where exactly you plan to place this feature on the website and when users can download the invoice? I think users can download the invoice after the payment, right? If that's correct, we're currently working on the payment integration. After it's completed, I'll let you know to work on it. Otherwise, please describe when users can download the invoice and other details.

**Comment by ParasY1724** [comment]
@mdazfar2  I was referring to Myorders page
![Screenshot From 2024-10-23 21-45-10](https://github.com/user-attachments/assets/e73e7bcb-f8b0-41fd-b192-be498d67c171)

 **But , I think it would be better to work on it after payment gateway is merged**

**Comment by mdazfar2** [comment]
Alright! @ParasY1724

Right now, I'll keep this issue open, and after the payment integration is done, I'll mention you here to work on that.
