### ISSUE TITLE
[Feat]: Chatbot

### ISSUE THREAD

**Issue by Poushmita** [mdazfar2/Ezyshop#914]
### Description

Want to add a chatbot in the website, which will look modern for any users.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Poushmita, ChatBOT is a very good feature, but I don’t think it is needed on our website right now. Once the website is fully functional and in working condition, I will let you know. Currently, we are working on the payment gateway, so I will inform you if there is a need in the future. Please raise any other issue, which I am happy to assign to you, but make sure the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_
