### ISSUE TITLE
[Feat] Social Icons

### ISSUE THREAD

**Issue by Dipeshdahiya** [mdazfar2/Ezyshop#920]
### Description

I would like to add social icons to the login page and the signup page for a better way to login and signup , i will make sure the buttons has the same theme as the site has , please assign this issue to me under gssoc.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Dipeshdahiya, that's a good suggestion, but have you noticed that major e-commerce websites mainly use phone number verification with SMS OTP? This is not feasible for us because it's a paid service, which is why we use email OTP verification for easy login and signup. I hope you understand why we’re not implementing this feature.

**Comment by Dipeshdahiya** [comment]
Okay understood. Is their any other issue from your side which is pending and you like someone to work on , is anything then please tell me i would be very happy to work on that issue instead.
