### ISSUE TITLE
[Feat] : Adding dummy stats in the about us page

### ISSUE THREAD

**Issue by VinayLodhi1712** [mdazfar2/Ezyshop#934]
### Description

[Feat] : Adding dummy stats in the about us page on scrolled up using react-countup library this will enhance user to shop with your website.

### Screenshots

![abo](https://github.com/user-attachments/assets/d50faa1f-9d66-42cf-aff8-5a6126200805)

https://github.com/user-attachments/assets/8200bbc3-317a-40fa-bbf5-6bff77e4a6ed

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @VinayLodhi1712, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. **Thank you!**
