### ISSUE TITLE
[Feat]:Add Multiple Languages Support 

### ISSUE THREAD

**Issue by jjf2009** [mdazfar2/Ezyshop#946]
### Description

People should be able to shop on Ezyshop even if there do not Know English 

### Screenshots

I will something like this to the navbar so users can choice the language 
![Uploading Screenshot 2024-10-23 222529.jpg…]()

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @jjf2009,The website requires multilingual support for global usage, where it's understood that everyone knows English, with just minor adjustments.

If we need this feature in the future, we will definitely let you know.

Please don't be discouraged. I need to close your issue. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and truly needs to be addressed on our website; otherwise, invalid issues will be closed. _Thank you!_
