### ISSUE TITLE
There is an old Logo of X (Twitter) in the social media icon

### ISSUE THREAD

**Issue by pankajsaini1** [mdazfar2/Ezyshop#95]
### Description

There is an old Logo of X (Twitter) in the social media icon 
i want to solve this issue.

### Screenshots

![Screenshot 2024-10-03 191039](https://github.com/user-attachments/assets/92a0b1bf-3291-4a8a-bd02-5d7921bd0ab8)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@pankajsaini1, do one thing: instead of the Twitter icon, add the `GitHub` icon and insert the Ezyshop GitHub repo link. In the `LinkedIn` icon, insert the LinkedIn link found in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md), and instead of Facebook, add the Discord icon and include the Discord invite link, which is also available in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md).

**Comment by Samyak137** [comment]
I have to work on that will you please assign it to me.

**Comment by Pariyul** [comment]
Hello sir , I have to work on that will you please assign it to me.

**Comment by pankajsaini1** [comment]
@mdazfar2 my pr is is merged but why there is no changes in website.

**Comment by pankajsaini1** [comment]
> @pankajsaini1, because you didn't update your branch, the current changes were removed and replaced with the previous ones. So, unfortunately, I had to revert all of your changes that I merged from your PR.

can i again raise a issue and make new pull request.

**Comment by mdazfar2** [comment]
@pankajsaini1 i reopened this issue and created PR referencing the same issue. 

---

### Changes description-

Instead of the Twitter icon, add the `GitHub` icon and insert the Ezyshop GitHub repo link. In the `LinkedIn` icon, insert the LinkedIn link found in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md), and instead of Facebook, add the Discord icon and include the Discord invite link, which is also available in the [README.md](https://github.com/mdazfar2/Ezyshop/blob/main/README.md).

**Comment by Pariyul** [comment]
Hello! I’m excited to work on this issue as a GSSOC'24 contributor. Could you please assign it to me?

**Comment by mdazfar2** [comment]
sure @Pariyul go ahead issue is assigned to you.

**Comment by Samyak137** [comment]
It looks interesting! will you please assign it to me.

**Comment by mdazfar2** [comment]
Hey @Samyak137, I appreciate your interest, but this issue is already assigned to two others. I will mention you in another issue if possible! Thank you.

**Comment by Samyak137** [comment]
Sure @mdazfar2 
Thank You!

**Comment by prisha-sh** [comment]
Hey, I'm quite familiar with and can solve your issue quickly, kindly assign it to me, I'm interested  !!!!

**Comment by mdazfar2** [comment]
no response closing issue for now
