### ISSUE TITLE
Improving the UI of the navbar

### ISSUE THREAD

**Issue by Aman-G-upta** [mdazfar2/Ezyshop#955]
![Screenshot 2024-10-25 080024](https://github.com/user-attachments/assets/910f5ca6-bcc7-4222-972d-34078f57fcf6)

"Due to the Sign Up and Login buttons, a horizontal scrollbar is appearing on the page, which makes the UI inconsistent. Please assign this issue to me under gssso extd24 , hactober fest ."

**Comment by mdazfar2** [comment]
Hey @Aman-G-upta, this is a very good feature, but it does not look good on our website. According to our website's design, a simpler effect and feature will look more attractive. So, as of now, I don’t think this issue is necessary for our website. Please work on any other issue that is needed and raise issues accordingly. ***Thank you!***I

**Comment by Aman-G-upta** [comment]
the login button is not properly visible and all the tabs are very very congested and there is no gap between the "Ezyshop" and the home tab

**Comment by mdazfar2** [comment]
@Aman-G-upta 


https://github.com/user-attachments/assets/801202f9-2cd8-43dd-9a51-184c364b1b1d
