### ISSUE TITLE
[Feat] Display the store's precise location 

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#966]
### Description

using the data of location of the seller, we can provide the precise location of the store on the seller's shop page on the main website

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by rajnish032** [comment]
assign to me

**Comment by mdazfar2** [comment]
Sorry @rajnish032, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. ***Thank you!***
