### ISSUE TITLE
[Feat] Implement contact us page

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#972]
### Description

currently, the contact us page doesn't work, I will make sure that whenever someone sends a query, it is received VIA email 

### Screenshots

![image](https://github.com/user-attachments/assets/5ff007ae-59cb-4c76-95e2-3bf8de550e8f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays You have raised a duplicate issue; it was already raised by someone else. 
- Look at all the issues, see which ones are available and which ones are not, and create issues accordingly.
- This is not the way to work on open source :)

**Comment by ShivanshPlays** [comment]
Okay I tried to look for a similar issue but didn't find the issue you are referring to at the time of raising this one, maybe I missed it

**Comment by ShivanshPlays** [comment]
@mdazfar2 please assign if no one has solved this till now otherwise close the issue

**Comment by mdazfar2** [comment]
@ShivanshPlays You are assigned.

Can you implement the newsletter functionality also, so that when a user enters their name and email and clicks the `subscribe` button, they receive an email from Ezyshop? Additionally, can the user details be stored in my MongoDB database to track subscriptions? If a user tries to subscribe again with an already registered email, a popup should appear saying, `Already subscribed to our newsletter`. Let me know if you can implement this.

<br/>


**Checkout the below demo video for better understand** 👇


<br>

https://github.com/user-attachments/assets/a7833364-4b0d-4821-85e4-dd20ac3df8b6
