### ISSUE TITLE
[Feat] Update schema of backend to accommodate user cart

### ISSUE THREAD

**Issue by ShivanshPlays** [mdazfar2/Ezyshop#973]
### Description

the current schema does not support the functionality of cart for users, I will modify the schema of DB to have a many to many relation between user and product.

### Screenshots

![image](https://github.com/user-attachments/assets/4fa226c0-dbe6-4377-a292-718d73926e5e)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@ShivanshPlays you are assigned.

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024

**Comment by mdazfar2** [comment]
Sorry @Shalinis19137, please don't be discouraged, but this issue is already assigned to someone. Only one person can work on a single issue at a time. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and really needs to be addressed on our website; otherwise, invalid issues will be closed. ***Thank you!***
