### ISSUE TITLE
Add language change button to your website

### ISSUE THREAD

**Issue by Antima2004** [mdazfar2/Ezyshop#988]
### Description

By adding language change button more user gets connected with your website. it will enhance your website.

### Screenshots

![Screenshot 2024-10-26 205815](https://github.com/user-attachments/assets/ef87f322-ae67-4e2b-868b-3f6b7d487672)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
Hey @Antima2004, The website requires multilingual support for global usage, where it's understood that everyone knows English, with just minor adjustments.

If we need this feature in the future, we will definitely let you know.

Please don't be discouraged. I need to close your issue. You can raise another issue, and I will be happy to assign it to you, but make sure that the issue you raise is valid and truly needs to be addressed on our website; otherwise, invalid issues will be closed. 

- Don't forget to give a star to our [repository](https://github.com/mdazfar2/ezyshop). 🌟

- Follow us on [LinkedIn](https://linkedin.com/company/Ezyshopz).

- Join our official [Discord](https://discord.gg/YnABU7tdU3) server where we can easily talk about how to enhance our project even better.


***Thank you!***


_Thank you!_
